export const SERVICES = [
  {
    id: 1,
    title: "Plumbing Services",
    description: "Expert plumbing solutions for your home or business.",
    category: "Home Services",
    tags: "plumbing, home repair",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 2,
    title: "Electrical Repairs",
    description: "Professional electrical repair services by certified electricians.",
    category: "Home Services",
    tags: "electrical, home repair",
    latitude: 40.7128,
    longitude: -74.0060,
  },
  {
    id: 3,
    title: "IT Support",
    description: "Comprehensive IT support services for businesses and individuals.",
    category: "Technology",
    tags: "IT, tech support",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 4,
    title: "Catering Services",
    description: "Delicious catering for events and special occasions.",
    category: "Food & Beverage",
    tags: "catering, events",
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    id: 5,
    title: "Fitness Training",
    description: "Personalized fitness training sessions for all fitness levels.",
    category: "Health & Fitness",
    tags: "fitness, personal training",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 6,
    title: "Gardening Services",
    description: "Professional gardening services to enhance your outdoor space.",
    category: "Home Services",
    tags: "gardening, landscaping",
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    id: 7,
    title: "Graphic Design",
    description: "Creative graphic design solutions for your brand and projects.",
    category: "Design & Creativity",
    tags: "graphic design, branding",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 8,
    title: "Car Repair",
    description: "Quality auto repair services for all makes and models.",
    category: "Automotive",
    tags: "car repair, maintenance",
    latitude: 40.7128,
    longitude: -74.0060,
  },
  {
    id: 9,
    title: "Dog Grooming",
    description: "Professional grooming services to keep your furry friend looking great.",
    category: "Pet Services",
    tags: "dog grooming, pet care",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 10,
    title: "Photography",
    description: "Capturing special moments with creative and professional photography.",
    category: "Arts & Photography",
    tags: "photography, events",
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    id: 11,
    title: "Home Cleaning",
    description: "Thorough and reliable home cleaning services for a tidy living space.",
    category: "Home Services",
    tags: "cleaning, home maintenance",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 12,
    title: "Computer Repair",
    description: "Swift and efficient computer repair services for your devices.",
    category: "Technology",
    tags: "computer repair, tech support",
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    id: 13,
    title: "Event Planning",
    description: "Expert event planning services to make your special occasion memorable.",
    category: "Events & Planning",
    tags: "event planning, coordination",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 14,
    title: "Tutoring",
    description: "Personalized tutoring services to help you excel in your studies.",
    category: "Education",
    tags: "tutoring, education",
    latitude: 40.7128,
    longitude: -74.0060,
  },
  {
    id: 15,
    title: "Massage Therapy",
    description: "Relaxing and rejuvenating massage therapy sessions for your well-being.",
    category: "Health & Wellness",
    tags: "massage, wellness",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 16,
    title: "Interior Design",
    description: "Transforming spaces with creative and stylish interior design services.",
    category: "Design & Creativity",
    tags: "interior design, home decor",
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    id: 17,
    title: "Personal Chef",
    description: "Exquisite dining experiences with a personal chef for your events.",
    category: "Food & Beverage",
    tags: "personal chef, catering",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 18,
    title: "Yoga Instruction",
    description: "Guided yoga sessions for relaxation and physical well-being.",
    category: "Health & Fitness",
    tags: "yoga, fitness",
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    id: 19,
    title: "Graphic Illustration",
    description: "Artistic graphic illustration services to bring your ideas to life.",
    category: "Arts & Design",
    tags: "graphic illustration, art",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 20,
    title: "Handyman Services",
    description: "Versatile handyman services for various home improvement tasks.",
    category: "Home Services",
    tags: "handyman, home repair",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 21,
    title: "Hair Styling",
    description: "Creative hair styling services for a fresh and stylish look.",
    category: "Beauty & Personal Care",
    tags: "hair styling, salon",
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    id: 22,
    title: "Language Tutoring",
    description: "Language tutoring services to help you become fluent in a new language.",
    category: "Education",
    tags: "language tutoring, language learning",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 23,
    title: "Carpentry",
    description: "Skilled carpentry services for custom woodworking projects.",
    category: "Home Services",
    tags: "carpentry, woodworking",
    latitude: 40.7128,
    longitude: -74.0060,
  },
  {
    id: 24,
    title: "Mobile App Development",
    description: "Innovative mobile app development services for your business or idea.",
    category: "Technology",
    tags: "app development, technology",
    latitude: 51.5074,
    longitude: -0.1278,
  },
  {
    id: 25,
    title: "Wedding Planning",
    description: "Expert wedding planning services to make your big day unforgettable.",
    category: "Events & Planning",
    tags: "wedding planning, events",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 26,
    title: "Personal Training",
    description: "Personalized fitness training sessions for achieving your health goals.",
    category: "Health & Fitness",
    tags: "personal training, fitness",
    latitude: 41.8781,
    longitude: -87.6298,
  },
  {
    id: 27,
    title: "Dance Instruction",
    description: "Fun and engaging dance instruction for individuals and groups.",
    category: "Arts & Entertainment",
    tags: "dance instruction, dance",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 28,
    title: "Content Writing",
    description: "Professional content writing services for your website or business.",
    category: "Writing & Content",
    tags: "content writing, writing",
    latitude: 37.7749,
    longitude: -122.4194,
  },
  {
    id: 29,
    title: "House Painting",
    description: "Quality house painting services to refresh and enhance your home.",
    category: "Home Services",
    tags: "painting, home improvement",
    latitude: 34.0522,
    longitude: -118.2437,
  },
  {
    id: 30,
    title: "Virtual Assistance",
    description: "Efficient virtual assistance services to support your business or tasks.",
    category: "Business Services",
    tags: "virtual assistance, business support",
    latitude: 51.5074,
    longitude: -0.1278,
  },
];
